// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// diff_mat
arma::mat diff_mat(arma::mat x);
RcppExport SEXP _specs_diff_mat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(diff_mat(x));
    return rcpp_result_gen;
END_RCPP
}
// embed_mat
arma::mat embed_mat(arma::mat x, const int p);
RcppExport SEXP _specs_embed_mat(SEXP xSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(embed_mat(x, p));
    return rcpp_result_gen;
END_RCPP
}
// cecm
Rcpp::List cecm(arma::vec y, arma::mat x, const int p, bool ADL);
RcppExport SEXP _specs_cecm(SEXP ySEXP, SEXP xSEXP, SEXP pSEXP, SEXP ADLSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< bool >::type ADL(ADLSEXP);
    rcpp_result_gen = Rcpp::wrap(cecm(y, x, p, ADL));
    return rcpp_result_gen;
END_RCPP
}
// specs_rcpp
Rcpp::List specs_rcpp(const arma::vec y, const arma::mat x, const int p, std::string deterministics, bool ADL, arma::vec weights, const double k_delta, const double k_pi, arma::vec lambda_g, arma::vec lambda_i, const double thresh, const double max_iter_delta, const double max_iter_pi, const double max_iter_gamma);
RcppExport SEXP _specs_specs_rcpp(SEXP ySEXP, SEXP xSEXP, SEXP pSEXP, SEXP deterministicsSEXP, SEXP ADLSEXP, SEXP weightsSEXP, SEXP k_deltaSEXP, SEXP k_piSEXP, SEXP lambda_gSEXP, SEXP lambda_iSEXP, SEXP threshSEXP, SEXP max_iter_deltaSEXP, SEXP max_iter_piSEXP, SEXP max_iter_gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< std::string >::type deterministics(deterministicsSEXP);
    Rcpp::traits::input_parameter< bool >::type ADL(ADLSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const double >::type k_delta(k_deltaSEXP);
    Rcpp::traits::input_parameter< const double >::type k_pi(k_piSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda_g(lambda_gSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda_i(lambda_iSEXP);
    Rcpp::traits::input_parameter< const double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< const double >::type max_iter_delta(max_iter_deltaSEXP);
    Rcpp::traits::input_parameter< const double >::type max_iter_pi(max_iter_piSEXP);
    Rcpp::traits::input_parameter< const double >::type max_iter_gamma(max_iter_gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(specs_rcpp(y, x, p, deterministics, ADL, weights, k_delta, k_pi, lambda_g, lambda_i, thresh, max_iter_delta, max_iter_pi, max_iter_gamma));
    return rcpp_result_gen;
END_RCPP
}
// specs_tr_rcpp
Rcpp::List specs_tr_rcpp(arma::vec y_d, arma::mat z_l, arma::mat w, std::string deterministics, bool ADL, arma::vec weights, const double k_delta, const double k_pi, arma::vec lambda_g, arma::vec lambda_i, const double thresh, const double max_iter_delta, const double max_iter_pi, const double max_iter_gamma);
RcppExport SEXP _specs_specs_tr_rcpp(SEXP y_dSEXP, SEXP z_lSEXP, SEXP wSEXP, SEXP deterministicsSEXP, SEXP ADLSEXP, SEXP weightsSEXP, SEXP k_deltaSEXP, SEXP k_piSEXP, SEXP lambda_gSEXP, SEXP lambda_iSEXP, SEXP threshSEXP, SEXP max_iter_deltaSEXP, SEXP max_iter_piSEXP, SEXP max_iter_gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y_d(y_dSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z_l(z_lSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type w(wSEXP);
    Rcpp::traits::input_parameter< std::string >::type deterministics(deterministicsSEXP);
    Rcpp::traits::input_parameter< bool >::type ADL(ADLSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const double >::type k_delta(k_deltaSEXP);
    Rcpp::traits::input_parameter< const double >::type k_pi(k_piSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda_g(lambda_gSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda_i(lambda_iSEXP);
    Rcpp::traits::input_parameter< const double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< const double >::type max_iter_delta(max_iter_deltaSEXP);
    Rcpp::traits::input_parameter< const double >::type max_iter_pi(max_iter_piSEXP);
    Rcpp::traits::input_parameter< const double >::type max_iter_gamma(max_iter_gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(specs_tr_rcpp(y_d, z_l, w, deterministics, ADL, weights, k_delta, k_pi, lambda_g, lambda_i, thresh, max_iter_delta, max_iter_pi, max_iter_gamma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_specs_diff_mat", (DL_FUNC) &_specs_diff_mat, 1},
    {"_specs_embed_mat", (DL_FUNC) &_specs_embed_mat, 2},
    {"_specs_cecm", (DL_FUNC) &_specs_cecm, 4},
    {"_specs_specs_rcpp", (DL_FUNC) &_specs_specs_rcpp, 14},
    {"_specs_specs_tr_rcpp", (DL_FUNC) &_specs_specs_tr_rcpp, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_specs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
