# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

diff_mat <- function(x) {
    .Call(`_specs_diff_mat`, x)
}

embed_mat <- function(x, p = 1L) {
    .Call(`_specs_embed_mat`, x, p)
}

cecm <- function(y, x, p, ADL) {
    .Call(`_specs_cecm`, y, x, p, ADL)
}

specs_rcpp <- function(y, x, p, deterministics, ADL, weights, k_delta, k_pi, lambda_g, lambda_i, thresh, max_iter_delta, max_iter_pi, max_iter_gamma) {
    .Call(`_specs_specs_rcpp`, y, x, p, deterministics, ADL, weights, k_delta, k_pi, lambda_g, lambda_i, thresh, max_iter_delta, max_iter_pi, max_iter_gamma)
}

specs_tr_rcpp <- function(y_d, z_l, w, deterministics, ADL, weights, k_delta, k_pi, lambda_g, lambda_i, thresh, max_iter_delta, max_iter_pi, max_iter_gamma) {
    .Call(`_specs_specs_tr_rcpp`, y_d, z_l, w, deterministics, ADL, weights, k_delta, k_pi, lambda_g, lambda_i, thresh, max_iter_delta, max_iter_pi, max_iter_gamma)
}

